# -*- coding: utf-8 -*-
"""RecoAgentver최종OOP+스키마/노드 버전의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUVBLKyXRB8Y9Z-2MkPTFV2Owb4Q9O3O
"""

# =========================
# ✅ 데이터베이스 (FAKE_DB)
# =========================
FAKE_DB = {
    "users": {
        1: {"user_id": 1, "diabetes": "N/A", "hypertension": "N/A", "kidneydisease": "N/A", "allergy": "N/A", "weight": 65.0},
        2: {"user_id": 2, "diabetes": "type2", "hypertension": "N/A", "kidneydisease": "N/A", "allergy": "milk", "weight": 72.3},
    },
    "final_profiles": {
        "0": {  # 당뇨 + 우유/땅콩 알러지
            "restricted_ingredients": ["우유", "땅콩"],
            "sugar": 5.0
        },
        "1": {  # 고혈압 + 새우 알러지
            "restricted_ingredients": ["새우"],
            "sodium": 2300.0,
            "potassium": 3500.0,
            "fat_ratio": 0.25
        },
    },
    "products": {
        "0": {
            "product_id": "201905000000",
            "name": "설화눈꽃팝김부각스낵",
            "brand": "설화",
            "category": "과자",
            "ingredients": ["찹쌀", "김", "참깨", "옥수수기름", "양파", "무", "대파", "천일염", "마늘", "새우", "멸치", "다시마", "건표고버섯", "둥굴레", "감초", "정제수"],
            "allergy": "없음",
            "trace": "null",
            "calories": 150, "sodium": 180, "carbohydrate": 20, "sugar": 1,
            "fat": 7, "trans_fat": 0, "saturated_fat": 1.2, "cholesterol": 5,
            "protein": 2, "phosphorus": 45, "calcium": 30, "potassium": 120,
            "inferred_types": ["low_sugar"]
        },
        "1": {
            "product_id": "201804000001",
            "name": "설화눈꽃팝김부각스낵 아몬드맛",
            "brand": "설화",
            "category": "과자",
            "ingredients": ["찹쌀", "김", "참깨", "아몬드", "양파", "무", "천일염", "새우", "멸치", "다시마", "정제수"],
            "allergy": "아몬드",
            "trace": "",
            "calories": 170, "sodium": 160, "carbohydrate": 18, "sugar": 1,
            "fat": 10, "trans_fat": 0, "saturated_fat": 1.0, "cholesterol": 3,
            "protein": 4, "phosphorus": 80, "calcium": 50, "potassium": 200,
            "inferred_types": ["low_sugar"]
        },
        "2": {
            "product_id": "201804000002",
            "name": "고들빼기김치",
            "brand": "남도미가",
            "category": "김치류",
            "ingredients": ["고들빼기", "멸치액", "염장새우", "양파", "혼합간장", "고춧가루", "마늘", "참깨", "물엿", "배즙", "당근"],
            "allergy": "새우,대두,밀",
            "trace": "밀, 땅콩, 복숭아, 토마토, 호두, 아황산류 혼입 가능",
            "calories": 45, "sodium": 850, "carbohydrate": 8, "sugar": 4,
            "fat": 0.5, "trans_fat": 0, "saturated_fat": 0.1, "cholesterol": 2,
            "protein": 2, "phosphorus": 35, "calcium": 40, "potassium": 320,
            "inferred_types": ["low_fat", "low_sugar", "high_sodium"]
        },
        "3": {
            "product_id": "199504000000",
            "name": "해태 허니버터칩",
            "brand": "해태",
            "category": "과자",
            "ingredients": ["감자", "혼합식용유", "허니버터맛시즈닝", "탈지분유(우유)", "버터혼합분말(대두)", "아카시아꿀", "고메버터(밀)"],
            "allergy": "알수없음",
            "trace": "null",
            "calories": 345, "sodium": 350, "carbohydrate": 30, "sugar": 7,
            "fat": 23, "trans_fat": 0.1, "saturated_fat": 8, "cholesterol": 10,
            "protein": 3, "phosphorus": 70, "calcium": 25, "potassium": 450,
            "inferred_types": ["high_fat"]
        },
        "4": {
            "product_id": "201405000000",
            "name": "헬로버블 라이스퍼프 양파맛",
            "brand": "헬로버블",
            "category": "과자",
            "ingredients": ["현미", "어니언시즈닝", "정백당", "리치버터분말", "양파분", "합성향료", "백미", "옥수수과립"],
            "allergy": "알수없음",
            "trace": "돼지고기, 땅콩, 복숭아, 아황산류, 호두 혼입 가능",
            "calories": 120, "sodium": 110, "carbohydrate": 22, "sugar": 3,
            "fat": 2.5, "trans_fat": 0, "saturated_fat": 0.5, "cholesterol": 0,
            "protein": 2, "phosphorus": 55, "calcium": 15, "potassium": 90,
            "inferred_types": ["low_fat", "low_sugar", "low_sodium"]
        },
        "5": {
            "product_id": "201105000000",
            "name": "두마리목장 콜비치즈",
            "brand": "두마리목장",
            "category": "유제품",
            "ingredients": ["원유(국산)99.9%", "우유응고효소", "유산균", "식염", "안나토색소"],
            "allergy": "우유함유",
            "trace": "null",
            "calories": 115, "sodium": 190, "carbohydrate": 1, "sugar": 0.5,
            "fat": 9, "trans_fat": 0.3, "saturated_fat": 6, "cholesterol": 30,
            "protein": 7, "phosphorus": 140, "calcium": 210, "potassium": 25,
            "inferred_types": ["low_sugar"]
        },
        "6": {
            "product_id": "201105000001",
            "name": "양반 바삭 튀김가루",
            "brand": "양반",
            "category": "기타가공품",
            "ingredients": ["밀가루", "변성전분", "베이킹파우더", "정제소금", "양파분말", "옥수수가루"],
            "allergy": "밀",
            "trace": "null",
            "calories": 350, "sodium": 650, "carbohydrate": 78, "sugar": 2,
            "fat": 1.2, "trans_fat": 0, "saturated_fat": 0.3, "cholesterol": 0,
            "protein": 7, "phosphorus": 95, "calcium": 20, "potassium": 110,
            "inferred_types": ["low_fat", "low_sugar", "high_carb", "high_sodium"]
        },
        "7": {
            "product_id": "201104000001",
            "name": "돈목살훈제바베큐스테이크",
            "brand": "옐로우팜",
            "category": "햄/비살균제품",
            "ingredients": ["돼지고기 96.68%", "스모크시즈닝", "분리대두단백", "토마토케찹", "아질산나트륨"],
            "allergy": "돼지고기,밀,우유,대두,쇠고기,토마토 함유",
            "trace": "null",
            "calories": 280, "sodium": 720, "carbohydrate": 5, "sugar": 2,
            "fat": 20, "trans_fat": 0, "saturated_fat": 7, "cholesterol": 65,
            "protein": 19, "phosphorus": 180, "calcium": 15, "potassium": 310,
            "inferred_types": ["low_sugar", "high_protein", "high_fat", "high_sodium"]
        },
        "8": {
            "product_id": "201104000002",
            "name": "태양초 고추장 골드",
            "brand": "해찬들",
            "category": "고추장",
            "ingredients": ["고춧가루", "물엿", "소맥분(밀)", "혼합양념", "밀쌀", "정제소금", "정백당"],
            "allergy": "알수없음",
            "trace": "null",
            "calories": 210, "sodium": 2400, "carbohydrate": 48, "sugar": 25,
            "fat": 1, "trans_fat": 0, "saturated_fat": 0.2, "cholesterol": 0,
            "protein": 4, "phosphorus": 90, "calcium": 35, "potassium": 450,
            "inferred_types": ["low_fat", "high_sugar", "high_sodium"]
        },
        "9": {
            "product_id": "201104000003",
            "name": "환타지 믹스너트",
            "brand": "환타지",
            "category": "땅콩 또는 견과류가공품",
            "ingredients": ["커피땅콩", "화이트볼", "찹쌀땅콩", "튀김땅콩", "로스티드피너츠", "바나나칩", "볶음아몬드", "꿀땅콩"],
            "allergy": "알수없음",
            "trace": "null",
            "calories": 520, "sodium": 280, "carbohydrate": 45, "sugar": 18,
            "fat": 34, "trans_fat": 0, "saturated_fat": 9, "cholesterol": 0,
            "protein": 14, "phosphorus": 310, "calcium": 75, "potassium": 580,
            "inferred_types": ["high_sugar", "high_protein", "high_fat", "high_potassium"]
        },
        "10": {
        "product_id": "201905000001",
        "name": "초코 크림빵",
        "brand": "OO베이커리",
        "category": "빵류",
        "ingredients": ["밀가루", "설탕", "코코아분말", "계란", "우유", "버터", "이스트"],
        "allergy": "밀,우유,계란",
        "trace": "null",
        "calories": 310.0, "sodium": 320.0, "carbohydrate": 45.0, "sugar": 18.0,
        "fat": 11.0, "trans_fat": 0.2, "saturated_fat": 5.0, "cholesterol": 35.0,
        "protein": 7.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    },
    "11": {
        "product_id": "201905000002",
        "name": "딸기 크림빵",
        "brand": "OO베이커리",
        "category": "빵",
        "ingredients": ["밀가루", "설탕", "딸기잼", "계란", "우유", "버터", "이스트"],
        "allergy": "밀,우유,계란",
        "trace": "null",
        "calories": 295.0, "sodium": 300.0, "carbohydrate": 44.0, "sugar": 17.0,
        "fat": 10.0, "trans_fat": 0.2, "saturated_fat": 4.8, "cholesterol": 30.0,
        "protein": 7.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    },
    "12": {
        "product_id": "201906000000",
        "name": "제로 탄산음료",
        "brand": "OO음료",
        "category": "탄산음료",
        "ingredients": ["정제수", "이산화탄소", "향료", "감미료", "산도조절제"],
        "allergy": "없음",
        "trace": "null",
        "calories": 0.0, "sodium": 15.0, "carbohydrate": 0.0, "sugar": 0.0,
        "fat": 0.0, "trans_fat": 0.0, "saturated_fat": 0.0, "cholesterol": 0.0,
        "protein": 0.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": ["low_sugar"]
    },
    "13": {
        "product_id": "201906000001",
        "name": "아메리카노 RTD",
        "brand": "OO커피",
        "category": "커피음료",
        "ingredients": ["정제수", "커피추출액"],
        "allergy": "없음",
        "trace": "null",
        "calories": 5.0, "sodium": 10.0, "carbohydrate": 1.0, "sugar": 0.0,
        "fat": 0.0, "trans_fat": 0.0, "saturated_fat": 0.0, "cholesterol": 0.0,
        "protein": 0.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": ["low_sugar"]
    },
    "14": {
        "product_id": "201906000002",
        "name": "허니버터 감자칩",
        "brand": "OO스낵",
        "category": "과자",
        "ingredients": ["감자", "식물성유지", "허니버터시즈닝", "설탕", "소금", "유청분말"],
        "allergy": "우유",
        "trace": "null",
        "calories": 530.0, "sodium": 450.0, "carbohydrate": 52.0, "sugar": 4.0,
        "fat": 34.0, "trans_fat": 0.0, "saturated_fat": 12.0, "cholesterol": 5.0,
        "protein": 6.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    },
    "15": {
        "product_id": "201906000003",
        "name": "치즈볼 스낵",
        "brand": "OO스낵",
        "category": "과자",
        "ingredients": ["옥수수분", "치즈시즈닝", "식물성유지", "소금"],
        "allergy": "우유",
        "trace": "null",
        "calories": 510.0, "sodium": 680.0, "carbohydrate": 55.0, "sugar": 2.0,
        "fat": 29.0, "trans_fat": 0.0, "saturated_fat": 9.0, "cholesterol": 10.0,
        "protein": 7.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": ["low_sugar"]
    },
    "16": {
        "product_id": "201906000004",
        "name": "딸기 아이스크림",
        "brand": "OO아이스",
        "category": "아이스크림",
        "ingredients": ["원유", "설탕", "딸기농축액", "유크림", "유화제"],
        "allergy": "우유",
        "trace": "null",
        "calories": 210.0, "sodium": 80.0, "carbohydrate": 24.0, "sugar": 20.0,
        "fat": 11.0, "trans_fat": 0.0, "saturated_fat": 7.0, "cholesterol": 25.0,
        "protein": 4.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    },
    "17": {
        "product_id": "201906000005",
        "name": "딸기 케이크",
        "brand": "OO베이커리",
        "category": "케이크",
        "ingredients": ["밀가루", "설탕", "계란", "우유", "생크림", "딸기"],
        "allergy": "밀,우유,계란",
        "trace": "null",
        "calories": 350.0, "sodium": 280.0, "carbohydrate": 48.0, "sugar": 28.0,
        "fat": 14.0, "trans_fat": 0.2, "saturated_fat": 7.0, "cholesterol": 55.0,
        "protein": 6.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    },
    "18": {
        "product_id": "201906000006",
        "name": "즉석 냉동만두",
        "brand": "OO푸드",
        "category": "냉동식품",
        "ingredients": ["밀가루", "돼지고기", "양배추", "부추", "간장", "마늘"],
        "allergy": "밀,대두",
        "trace": "null",
        "calories": 260.0, "sodium": 720.0, "carbohydrate": 33.0, "sugar": 2.0,
        "fat": 9.0, "trans_fat": 0.0, "saturated_fat": 3.0, "cholesterol": 25.0,
        "protein": 11.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": ["low_sugar"]
    },
    "19": {
        "product_id": "201906000007",
        "name": "냉동 피자",
        "brand": "OO푸드",
        "category": "냉동식품",
        "ingredients": ["밀가루", "토마토소스", "치즈", "햄", "양파", "피망"],
        "allergy": "밀,우유",
        "trace": "null",
        "calories": 340.0, "sodium": 900.0, "carbohydrate": 40.0, "sugar": 6.0,
        "fat": 14.0, "trans_fat": 0.2, "saturated_fat": 6.0, "cholesterol": 30.0,
        "protein": 14.0, "phosphorus": None, "calcium": None, "potassium": None,
        "inferred_types": []
    }
    }
}

# =========================
# ✅ 사전 (Lexicons)
# =========================
TASTE_LEXICON = {
    "choco": ["초코", "초콜릿", "코코아", "카카오", "가나슈", "브라우니", "choco", "chocolate", "cocoa", "cacao"],
    "vanilla": ["바닐라", "vanilla"],
    "strawberry": ["딸기", "스트로베리", "strawberry"],
    "caramel": ["카라멜", "캐러멜", "caramel"],
    "honey": ["꿀", "허니", "honey"],
    "banana": ["바나나", "banana"],
    "apple": ["사과", "애플", "apple"],
    "peach": ["복숭아", "피치", "peach"],
    "grape": ["포도", "그레이프", "머스캣", "grape", "muscat"],
    "mango": ["망고", "mango"],
    "pineapple": ["파인애플", "pineapple"],
    "melon": ["멜론", "허니듀", "melon", "honeydew"],
    "berry_mix": ["베리", "블루베리", "라즈베리", "크랜베리", "berry", "blueberry", "raspberry", "cranberry"],
    "cookies_cream": ["쿠키앤크림", "쿠앤크", "cookies&cream", "cookies and cream"],
    "mint_choco": ["민트초코", "민초", "mint choco", "mint chocolate"],
    "cinnamon": ["시나몬", "계피", "cinnamon"],
    "coffee": ["커피", "콜드브루", "에스프레소", "espresso", "coffee", "cold brew", "coldbrew"],
    "latte": ["라떼", "latte"],
    "americano": ["아메리카노", "americano"],
    "mocha": ["모카", "mocha"],
    "hazelnut": ["헤이즐넛", "hazelnut"],
    "macadamia": ["마카다미아", "macadamia"],
    "green_tea": ["녹차", "말차", "그린티", "matcha", "green tea", "greentea"],
    "black_tea": ["홍차", "블랙티", "얼그레이", "다즐링", "black tea", "earl grey", "darjeeling"],
    "milk_tea": ["밀크티", "milk tea", "bubble tea", "버블티", "타피오카"],
    "herbal_tea": ["허브", "캐모마일", "페퍼민트", "루이보스", "herbal", "chamomile", "peppermint", "rooibos"],
    "lemon": ["레몬", "lemon"],
    "lime": ["라임", "lime"],
    "grapefruit": ["자몽", "grapefruit"],
    "orange": ["오렌지", "orange"],
    "yuzu": ["유자", "yuzu"],
    "citron": ["시트러스", "감귤", "귤", "citrus", "tangerine", "mandarin"],
    "sour": ["새콤", "상큼", "사워", "sour", "tart"],
    "yogurt_tang": ["요거트향", "요구르트맛", "yogurt flavor"],
    "salty": ["짭짤", "소금", "솔트", "salt", "salty"],
    "butter": ["버터", "butter"],
    "cheese": ["치즈", "체다", "크림치즈", "파마산", "cheese", "cheddar", "cream cheese", "parmesan"],
    "corn": ["콘", "옥수수", "corn"],
    "potato": ["감자", "potato"],
    "bbq": ["바베큐", "바비큐", "bbq", "barbecue"],
    "smoke": ["스모크", "훈제", "smoked", "smoke"],
    "garlic": ["마늘", "갈릭", "garlic"],
    "onion": ["양파", "어니언", "onion"],
    "mustard": ["머스터드", "mustard"],
    "mayo": ["마요", "마요네즈", "mayo", "mayonnaise"],
    "ketchup": ["케첩", "케찹", "ketchup"],
    "soy_sauce": ["간장", "soy sauce", "shoyu"],
    "sesame": ["참깨", "깨", "sesame"],
    "seaweed": ["김", "해조", "seaweed", "nori"],
    "wasabi": ["와사비", "wasabi"],
    "spicy": ["매운", "매콤", "얼큰", "spicy", "hot"],
    "pepper": ["후추", "블랙페퍼", "pepper", "black pepper"],
    "chili": ["고추", "칠리", "chili", "chilli"],
    "gochujang": ["고추장", "gochujang"],
    "kimchi": ["김치", "kimchi"],
    "tteokbokki": ["떡볶이", "tteokbokki"],
    "mala": ["마라", "화자오", "mala", "huajiao", "sichuan pepper"],
    "curry": ["카레", "커리", "curry"],
    "jalapeno": ["할라피뇨", "jalapeno"],
    "beef": ["소고기", "비프", "beef"],
    "pork": ["돼지고기", "포크", "pork"],
    "chicken": ["치킨", "닭", "chicken"],
    "seafood": ["해물", "씨푸드", "새우", "오징어", "게", "seafood", "shrimp", "squid", "crab"],
    "anchovy": ["멸치", "anchovy"],
    "mushroom": ["버섯", "표고", "mushroom", "shiitake"],
    "almond": ["아몬드", "almond"],
    "peanut": ["땅콩", "피넛", "peanut"],
    "walnut": ["호두", "walnut"],
    "coconut": ["코코넛", "coconut"],
    "oat": ["오트", "귀리", "oat"],
}

TYPE_LEXICON = {
    "carbonated": ["탄산", "스파클링", "소다", "cola", "coke", "sparkling", "soda"],
    "zero_sugar": ["제로", "무설탕", "설탕무첨가", "sugar free", "zero sugar", "no sugar"],
    "low_sugar_claim": ["저당", "low sugar", "reduced sugar"],
    "caffeinated": ["카페인", "caffeine"],
    "decaf": ["디카페인", "decaf", "de-caf", "deca"],
    "energy_drink": ["에너지", "에너지드링크", "energy", "energy drink"],
    "sports_drink": ["이온", "스포츠", "isotonic", "sports drink"],
    "protein_drink": ["프로틴", "단백질", "protein", "whey"],
    "tea_bottled": ["티", "차", "보틀티", "bottled tea"],
    "milk_beverage": ["우유", "밀크", "milk"],
    "chip": ["칩", "포테이토칩", "감자칩", "chip"],
    "cracker": ["크래커", "비스킷", "cracker", "biscuit"],
    "cookie": ["쿠키", "cookie"],
    "chocolate_snack": ["초콜릿", "초코바", "초코", "chocolate bar"],
    "jelly": ["젤리", "구미", "gummy", "jelly"],
    "candy": ["캔디", "사탕", "candy"],
    "nuts_snack": ["견과", "너트", "nuts"],
    "ramen": ["라면", "ramen"],
    "cup_noodle": ["컵라면", "용기면", "cup noodle", "cup ramen"],
    "udon": ["우동", "udon"],
    "soba": ["소바", "메밀", "soba", "buckwheat"],
    "pasta": ["파스타", "스파게티", "pasta", "spaghetti"],
    "rice_noodle": ["쌀국수", "pho", "rice noodle"],
    "milk": ["우유", "milk"],
    "yogurt": ["요거트", "요구르트", "yogurt"],
    "greek_yogurt": ["그릭", "greek"],
    "cheese_product": ["치즈", "cheese"],
    "butter_product": ["버터", "butter"],
    "lactose_free": ["락토프리", "lactose free"],
    "hot_sauce": ["핫소스", "hot sauce"],
    "gochujang_sauce": ["고추장", "gochujang"],
    "soy_sauce_type": ["간장", "soy sauce"],
    "mayo_type": ["마요", "마요네즈", "mayo", "mayonnaise"],
    "ketchup_type": ["케찹", "케첩", "ketchup"],
    "mustard_type": ["머스터드", "mustard"],
    "dressing": ["드레싱", "dressing"],
    "powder_seasoning": ["가루", "시즈닝", "seasoning", "powder"],
    "bread": ["빵", "식빵", "바게트", "bread", "baguette"],
    "cake": ["케이크", "cake"],
    "donut": ["도넛", "도너츠", "donut"],
    "pastry": ["페이스트리", "크루아상", "pastry", "croissant"],
    "ice_cream": ["아이스크림", "ice cream"],
    "dessert": ["디저트", "dessert"],
    "frozen_meal": ["냉동", "frozen", "냉동식품"],
    "dumpling": ["만두", "dumpling", "gyoza"],
    "pizza": ["피자", "pizza"],
    "fried_food": ["튀김", "치킨", "돈까스", "fried", "katsu"],
    "ready_to_eat": ["간편식", "즉석", "ready to eat", "rte", "즉석조리"],
}


# 맛 태그를 추출할 대상 카테고리 리스트 정의
SNACK_CATEGORIES = [
    "과자", "빵류", "빵", "케이크", "아이스크림",
    "탄산음료", "커피음료", "땅콩 또는 견과류가공품", "디저트"
]


CATEGORY_NEIGHBORS = {
    "음료": ["빵/디저트", "과자/스낵", "유제품/요거트"],
    "과자/스낵": ["음료", "빵/디저트", "유제품/요거트"],
    "면": ["소스/조미료", "냉동식품"],
    "유제품/요거트": ["빵/디저트", "과자/스낵", "음료"],
    "소스/조미료": ["면", "냉동식품"],
    "빵/디저트": ["음료", "유제품/요거트", "과자/스낵"],
    "냉동식품": ["면", "소스/조미료"],
}

import math
from typing import Dict, Any, List, Set, Optional, TypedDict


# =========================
# ✅ sub에게 넘길 스키마
# =========================
class Candidate(TypedDict):
    product_id: int
    rank: int  # 1..K

class RecoToSubPayload(TypedDict):
    candidates: List[Candidate]


# =========================
# ✅ Reco Engine (OOP)
# =========================
class RecoEngine:
    def __init__(
        self,
        fake_db: Dict[str, Any],
        taste_lexicon: Dict[str, List[str]],
        type_lexicon: Dict[str, List[str]],
        snack_categories: List[str],
        category_neighbors: Dict[str, List[str]],
        generic_taste_stop: Optional[Set[str]] = None,
    ):
        self.fake_db = fake_db
        self.taste_lexicon = taste_lexicon
        self.type_lexicon = type_lexicon
        self.snack_categories = snack_categories

        self.category_neighbors = self.make_neighbors_symmetric(category_neighbors)
        self.generic_taste_stop = generic_taste_stop or {
            "butter", "corn", "potato", "salty", "milk", "sugar", "wheat", "soy",
            "sesame", "seaweed"
        }

        # 최종 인덱스 DB
        self.final_db: Dict[int, Dict[str, Any]] = {}

    # -------------------------
    # Utils (원래 로직 그대로)
    # -------------------------
    @staticmethod
    def norm_cat(x: Any) -> str:
        return (x or "").strip().lower()

    def extract_taste_tags(self, text: str) -> List[str]:
        text_l = (text or "").lower()
        tags = []
        for tag, kws in self.taste_lexicon.items():
            for kw in kws:
                if kw.lower() in text_l:
                    tags.append(tag)
                    break
        return sorted(set(tags))

    def extract_lexicon_tags(self, text: str, lexicon: Dict[str, List[str]]) -> List[str]:
        # (현재 코드에서는 TYPE_LEXICON 등 다른 용도로 쓸 수 있어서 유지)
        text_l = (text or "").lower()
        tags: List[str] = []
        for tag, kws in lexicon.items():
            for kw in kws:
                if kw.lower() in text_l:
                    tags.append(tag)
                    break
        return sorted(set(tags))

    @staticmethod
    def token_overlap_score(a_text: str, b_text: str) -> int:
        a = set((a_text or "").lower().split())
        b = set((b_text or "").lower().split())
        return len(a & b)

    @staticmethod
    def make_neighbors_symmetric(neighbors: Dict[str, List[str]]) -> Dict[str, List[str]]:
        out = {k: list(v) for k, v in neighbors.items()}
        for a, bs in neighbors.items():
            for b in bs:
                out.setdefault(b, [])
                if a not in out[b]:
                    out[b].append(a)
        return out

    @staticmethod
    def _alloc_counts(k: int, weights: List[float]) -> List[int]:
        """k를 weights 비율로 정수 개수로 배분(합이 k가 되도록)"""
        raw = [k * w for w in weights]
        base = [int(math.floor(x)) for x in raw]
        remain = k - sum(base)

        frac = [(raw[i] - base[i], i) for i in range(len(weights))]
        frac.sort(reverse=True)
        for _, i in frac[:remain]:
            base[i] += 1
        return base

    def build_index_text(self, p: Dict[str, Any]) -> str:
        name = p.get("name", "")
        brand = p.get("brand", "")
        ingredients_list = p.get("ingredients", [])
        ing = " ".join(ingredients_list)
        cat = p.get("category", "")

        # 1) 기본 텍스트 구성
        base_text = f"{name} {brand} {ing}"

        # 2) 조건부 맛 태그 추출 (카테고리 제한) - 기존 로직 유지
        taste_tags: List[str] = []
        if any(snack_cat in cat for snack_cat in self.snack_categories):
            taste_tags = self.extract_taste_tags(base_text)

        # 3) 텍스트 조립
        taste_text = " ".join([f"taste:{t}" for t in taste_tags]) if taste_tags else ""
        cat_text = f"category:{cat}" if cat else "category:unknown"

        return " ".join([
            f"name:{name}",
            f"brand:{brand}",
            f"ingredients:{ing}",
            taste_text,
            cat_text,
        ]).strip()

    def get_taste_tag_set(self, p: Dict[str, Any]) -> Set[str]:
        toks = (p.get("index_text") or "").lower().split()
        return {t.split("taste:", 1)[1] for t in toks if t.startswith("taste:")}

    def filtered_taste_set(self, p: Dict[str, Any]) -> Set[str]:
        tastes = self.get_taste_tag_set(p)
        return {t for t in tastes if t not in self.generic_taste_stop}

    # -------------------------
    # Build final_db
    # -------------------------
    def build_final_db(self) -> Dict[int, Dict[str, Any]]:
        self.final_db = {}
        products = self.fake_db.get("products", {})

        for pid, p in products.items():
            pid_int = int(pid)
            index_text = self.build_index_text(p)

            self.final_db[pid_int] = {
                **p,  # 원본 유지
                "product_id": pid_int,
                "index_text": index_text,
                # ✅ allergen_tags 제거됨
            }

        return self.final_db

    # -------------------------
    # Retrieval (로직 그대로)
    # -------------------------
    def retrieve_candidates_v1_light_unified_k(
        self,
        clicked_product_id: int,
        k: int = 3,
        weights: List[float] = [0.6, 0.3, 0.1],  # bucket1, bucket2, bucket3
    ) -> List[Dict[str, Any]]:

        clicked = self.final_db.get(clicked_product_id)
        if not clicked:
            return []

        clicked_cat = self.norm_cat(clicked.get("category"))
        clicked_tastes = self.get_taste_tag_set(clicked)
        clicked_text = clicked.get("index_text") or ""
        neighbor_set = {self.norm_cat(c) for c in self.category_neighbors.get(clicked_cat, [])}

        bucket1, bucket2, bucket3, bucket4 = [], [], [], []

        for pid, p in self.final_db.items():
            if pid == clicked_product_id:
                continue

            cat = self.norm_cat(p.get("category"))
            tastes = self.get_taste_tag_set(p)

            taste_overlap = len(clicked_tastes & tastes)
            fallback = self.token_overlap_score(clicked_text, p.get("index_text") or "")

            row = {
                "product_id": pid,
                "name": p.get("name"),
                "category": cat,
                "tastes": sorted(tastes),
                "taste_score": taste_overlap,
                "fallback_score": fallback,
                "final_score": (taste_overlap * 10) + fallback,
            }

            if cat == clicked_cat:
                (bucket1 if taste_overlap > 0 else bucket2).append(row)
            elif cat in neighbor_set:
                (bucket3 if taste_overlap > 0 else bucket4).append(row)
            else:
                bucket4.append(row)

        def sort_key(r):
            return (r["taste_score"], r["fallback_score"], -r["product_id"])

        for b in (bucket1, bucket2, bucket3, bucket4):
            b.sort(key=sort_key, reverse=True)

        # ✅ k로부터 자동으로 n1,n2,n3 계산 (기존 로직)
        n1, n2, n3 = self._alloc_counts(k, weights)

        picked = bucket1[:n1] + bucket2[:n2] + bucket3[:n3]

        # 부족하면 bucket4로 채워서 딱 k 맞춤
        if len(picked) < k:
            picked += bucket4[: (k - len(picked))]

        return picked[:k]

    # -------------------------
    # ✅ sub에게 넘길 payload + debug 생성
    # -------------------------
    def run(
        self,
        clicked_product_id: int,
        k: int = 5,
        weights: List[float] = [0.6, 0.3, 0.1],
    ) -> tuple[RecoToSubPayload, Dict[str, Any]]:

        if not self.final_db:
            self.build_final_db()

        clicked = self.final_db.get(clicked_product_id)
        res = self.retrieve_candidates_v1_light_unified_k(
            clicked_product_id=clicked_product_id,
            k=k,
            weights=weights
        )

        # ✅ sub용 payload (스키마 고정)
        reco_to_sub: RecoToSubPayload = {
            "candidates": [
                {"product_id": r["product_id"], "rank": i + 1}
                for i, r in enumerate(res)
            ]
        }

        # ✅ 디버그(원하는 만큼 넣어도 sub에는 안 보냄)
        reco_debug: Dict[str, Any] = {
            "clicked": {
                "product_id": clicked_product_id,
                "name": clicked.get("name") if clicked else None,
                "category": self.norm_cat(clicked.get("category")) if clicked else None,
                "tastes": sorted(self.get_taste_tag_set(clicked)) if clicked else [],
            },
            "k": k,
            "weights": weights,
            "candidates_detail": res,  # taste_score/fallback_score/final_score 포함
        }

        return reco_to_sub, reco_debug


# =========================
# ✅ 사용 예시
# =========================
engine = RecoEngine(
    fake_db=FAKE_DB,
    taste_lexicon=TASTE_LEXICON,
    type_lexicon=TYPE_LEXICON,
    snack_categories=SNACK_CATEGORIES,
    category_neighbors=CATEGORY_NEIGHBORS,
)

reco_to_sub, reco_debug = engine.run(clicked_product_id=10, k=5)
print(reco_to_sub)

from typing import TypedDict, Any, Dict, Optional, List

# -------------------------
# sub에게 넘길 payload 스키마(너가 쓰는 그대로)
# -------------------------
class Candidate(TypedDict):
    product_id: int
    rank: int

class RecoToSubPayload(TypedDict):
    candidates: List[Candidate]

# -------------------------
# LangGraph 스타일의 "State"
# -------------------------
class RecoState(TypedDict, total=False):
    # input
    clicked_product_id: int
    k: int
    weights: List[float]

    # output
    reco_to_sub: RecoToSubPayload
    reco_debug: Dict[str, Any]

    # error
    error: Optional[str]


# -------------------------
# ✅ 진짜 "노드": state -> state
# -------------------------
def reco_node(state: RecoState, engine: "RecoEngine") -> RecoState:
    try:
        clicked_product_id = state["clicked_product_id"]
        k = state.get("k", 5)
        weights = state.get("weights", [0.6, 0.3, 0.1])

        reco_to_sub, reco_debug = engine.run(
            clicked_product_id=clicked_product_id,
            k=k,
            weights=weights
        )

        state["reco_to_sub"] = reco_to_sub
        state["reco_debug"] = reco_debug
        state["error"] = None
        return state

    except Exception as e:
        state["error"] = f"[reco_node] {type(e).__name__}: {e}"
        return state

# ✅ 엔진 생성 (너 코드 그대로)
engine = RecoEngine(
    fake_db=FAKE_DB,
    taste_lexicon=TASTE_LEXICON,
    type_lexicon=TYPE_LEXICON,
    snack_categories=SNACK_CATEGORIES,
    category_neighbors=CATEGORY_NEIGHBORS,
)

# ✅ "그래프 state" 처럼 입력 준비
state: RecoState = {
    "clicked_product_id": 10,
    "k": 5,
    "weights": [0.6, 0.3, 0.1],
}

# ✅ 노드 실행
state = reco_node(state, engine)

# ✅ 에러 체크
if state.get("error"):
    print("ERROR:", state["error"])
else:
    print("=== reco_to_sub (sub에게 전달) ===")
    print(state["reco_to_sub"])

    print("\n=== reco_debug (개발자 확인용) ===")
    for r in state["reco_debug"]["candidates_detail"]:
        print(f"- {r['product_id']} {r['name']}"
              f" | taste_score={r['taste_score']}"
              f" | fallback_score={r['fallback_score']}"
              f" | final_score={r['final_score']:.2f}"
              f" | tastes={r['tastes']}")