import { Product, Category } from "./types";

export const categories: Category[] = [
  { category_id: 1, name: "도시락·간편식", supercategory: "가공식품DB" },
  { category_id: 2, name: "단백질·보충제", supercategory: "가공식품DB" },
  { category_id: 3, name: "샐러드", supercategory: "가공식품DB" },
  { category_id: 4, name: "음료·주스", supercategory: "가공식품DB" },
  { category_id: 5, name: "과자·간식", supercategory: "가공식품DB" },
  { category_id: 6, name: "유제품", supercategory: "가공식품DB" },
  { category_id: 7, name: "건강식품", supercategory: "가공식품DB" },
  { category_id: 8, name: "냉동식품", supercategory: "가공식품DB" },
];

export const products: Product[] = [
  {
    product_id: 10042,
    name: "닭가슴살 샐러드",
    brand: "랭킹닭컴",
    category_id: 3,
    image_url: "https://picsum.photos/seed/salad1/400/500",
    is_active: true,
    quantity: 150,
    price: 6900,
    discount_rate: 10,
    original_price: 7700,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-02-10T14:32:00Z",
    nutrition: {
      rawmtrl: "닭가슴살(국내산), 양상추, 방울토마토, 올리브오일, 레몬즙, 소금, 후추",
      allergymtrl: "닭고기",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 200,
      calories_kcal: 180,
      protein_g: 24,
      fat_g: 6,
      ash_g: 2,
      carbohydrate_g: 8,
      sugar_g: 3,
      sodium_mg: 420,
      cholesterol_mg: 65,
      saturated_fat_g: 1,
      trans_fat_g: 0,
      gi: 35,
      gl: 3,
    },
    description: "국내산 닭가슴살로 만든 신선한 샐러드입니다. 다이어트와 건강관리에 최적화된 저칼로리 고단백 식품입니다.",
  },
  {
    product_id: 10043,
    name: "통밀 현미 도시락",
    brand: "잇메이트",
    category_id: 1,
    image_url: "https://picsum.photos/seed/lunch1/400/500",
    is_active: true,
    quantity: 200,
    price: 5500,
    discount_rate: 15,
    original_price: 6500,
    created_at: "2025-01-20T09:00:00Z",
    updated_at: "2025-02-12T10:00:00Z",
    nutrition: {
      rawmtrl: "현미(국내산), 닭가슴살, 브로콜리, 당근, 참기름",
      allergymtrl: "닭고기",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 250,
      calories_kcal: 350,
      protein_g: 28,
      fat_g: 8,
      ash_g: 3,
      carbohydrate_g: 42,
      sugar_g: 4,
      sodium_mg: 520,
      cholesterol_mg: 55,
      saturated_fat_g: 2,
      trans_fat_g: 0,
      gi: 50,
      gl: 10,
    },
    description: "통밀과 현미로 만든 건강 도시락. 든든한 한 끼를 책임지는 고단백 식단입니다.",
  },
  {
    product_id: 10044,
    name: "프로틴 쉐이크 초코",
    brand: "마이프로틴",
    category_id: 2,
    image_url: "https://picsum.photos/seed/protein1/400/500",
    is_active: true,
    quantity: 300,
    price: 39900,
    discount_rate: 20,
    original_price: 49900,
    created_at: "2025-01-10T09:00:00Z",
    updated_at: "2025-02-15T09:00:00Z",
    nutrition: {
      rawmtrl: "유청단백질(미국산), 코코아분말, 수크랄로스, 대두레시틴",
      allergymtrl: "우유, 대두",
      serving_size: 30,
      reference_intake: 1,
      food_weight: 1000,
      calories_kcal: 120,
      protein_g: 21,
      fat_g: 2,
      ash_g: 1,
      carbohydrate_g: 5,
      sugar_g: 1,
      sodium_mg: 100,
      cholesterol_mg: 30,
      saturated_fat_g: 1,
      trans_fat_g: 0,
      gi: 25,
      gl: 1,
    },
    description: "고순도 유청 단백질로 만든 초코맛 프로틴 쉐이크. 운동 후 근육 회복에 탁월합니다.",
  },
  {
    product_id: 10045,
    name: "그릭요거트 플레인",
    brand: "풀무원",
    category_id: 6,
    image_url: "https://picsum.photos/seed/yogurt1/400/500",
    is_active: true,
    quantity: 100,
    price: 3200,
    discount_rate: 0,
    original_price: 3200,
    created_at: "2025-01-25T09:00:00Z",
    updated_at: "2025-02-10T09:00:00Z",
    nutrition: {
      rawmtrl: "원유(국내산), 탈지분유, 유산균",
      allergymtrl: "우유",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 100,
      calories_kcal: 95,
      protein_g: 10,
      fat_g: 3,
      ash_g: 0.8,
      carbohydrate_g: 6,
      sugar_g: 5,
      sodium_mg: 45,
      cholesterol_mg: 10,
      saturated_fat_g: 2,
      trans_fat_g: 0,
      gi: 20,
      gl: 1,
    },
    description: "농후한 맛의 그릭요거트. 높은 단백질 함량으로 건강한 간식을 즐겨보세요.",
  },
  {
    product_id: 10046,
    name: "저염 김치찌개",
    brand: "비비고",
    category_id: 1,
    image_url: "https://picsum.photos/seed/kimchi1/400/500",
    is_active: true,
    quantity: 180,
    price: 4800,
    discount_rate: 5,
    original_price: 5100,
    created_at: "2025-02-01T09:00:00Z",
    updated_at: "2025-02-18T09:00:00Z",
    nutrition: {
      rawmtrl: "배추김치(국내산), 돼지고기, 두부, 대파, 고춧가루",
      allergymtrl: "돼지고기, 대두",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 300,
      calories_kcal: 120,
      protein_g: 8,
      fat_g: 5,
      ash_g: 2,
      carbohydrate_g: 10,
      sugar_g: 4,
      sodium_mg: 380,
      cholesterol_mg: 25,
      saturated_fat_g: 2,
      trans_fat_g: 0,
      gi: 40,
      gl: 4,
    },
    description: "나트륨을 줄인 건강한 김치찌개. 진한 맛은 그대로, 염분은 낮춘 건강 가정식입니다.",
  },
  {
    product_id: 10047,
    name: "무설탕 아몬드 밀크",
    brand: "매일유업",
    category_id: 4,
    image_url: "https://picsum.photos/seed/almond1/400/500",
    is_active: true,
    quantity: 250,
    price: 2800,
    discount_rate: 0,
    original_price: 2800,
    created_at: "2025-01-28T09:00:00Z",
    updated_at: "2025-02-14T09:00:00Z",
    nutrition: {
      rawmtrl: "아몬드(미국산), 정제수, 해바라기유, 칼슘",
      allergymtrl: "견과류",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 190,
      calories_kcal: 25,
      protein_g: 1,
      fat_g: 1.5,
      ash_g: 0.3,
      carbohydrate_g: 1,
      sugar_g: 0,
      sodium_mg: 80,
      cholesterol_mg: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      gi: 25,
      gl: 0,
    },
    description: "무설탕 아몬드 밀크. 유당 불내증이 있는 분들도 안심하고 드실 수 있습니다.",
  },
  {
    product_id: 10048,
    name: "곤약 젤리 복숭아",
    brand: "오리온",
    category_id: 5,
    image_url: "https://picsum.photos/seed/jelly1/400/500",
    is_active: true,
    quantity: 120,
    price: 1500,
    discount_rate: 0,
    original_price: 1500,
    created_at: "2025-02-05T09:00:00Z",
    updated_at: "2025-02-19T09:00:00Z",
    nutrition: {
      rawmtrl: "곤약분말, 복숭아농축액, 구연산, 비타민C",
      allergymtrl: "복숭아",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 130,
      calories_kcal: 10,
      protein_g: 0,
      fat_g: 0,
      ash_g: 0,
      carbohydrate_g: 3,
      sugar_g: 1,
      sodium_mg: 15,
      cholesterol_mg: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      gi: 10,
      gl: 0,
    },
    description: "복숭아맛 곤약젤리. 칼로리 걱정 없이 즐기는 건강 간식입니다.",
  },
  {
    product_id: 10049,
    name: "퀴노아 현미 밥",
    brand: "오뚜기",
    category_id: 8,
    image_url: "https://picsum.photos/seed/quinoa1/400/500",
    is_active: true,
    quantity: 200,
    price: 2200,
    discount_rate: 10,
    original_price: 2500,
    created_at: "2025-01-18T09:00:00Z",
    updated_at: "2025-02-16T09:00:00Z",
    nutrition: {
      rawmtrl: "현미(국내산), 퀴노아, 찹쌀, 정제수",
      allergymtrl: "",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 210,
      calories_kcal: 170,
      protein_g: 4,
      fat_g: 1,
      ash_g: 0.5,
      carbohydrate_g: 37,
      sugar_g: 0,
      sodium_mg: 5,
      cholesterol_mg: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      gi: 48,
      gl: 8,
    },
    description: "슈퍼푸드 퀴노아와 현미로 만든 건강 즉석밥. 간편하게 영양을 챙기세요.",
  },
  {
    product_id: 10050,
    name: "콜드브루 블랙커피",
    brand: "스타벅스",
    category_id: 4,
    image_url: "https://picsum.photos/seed/coffee1/400/500",
    is_active: true,
    quantity: 350,
    price: 3500,
    discount_rate: 0,
    original_price: 3500,
    created_at: "2025-02-02T09:00:00Z",
    updated_at: "2025-02-18T09:00:00Z",
    nutrition: {
      rawmtrl: "커피추출액(콜롬비아산), 정제수",
      allergymtrl: "",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 275,
      calories_kcal: 5,
      protein_g: 0,
      fat_g: 0,
      ash_g: 0,
      carbohydrate_g: 1,
      sugar_g: 0,
      sodium_mg: 10,
      cholesterol_mg: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      gi: 0,
      gl: 0,
    },
    description: "깊고 풍부한 맛의 콜드브루 블랙커피. 당류 없이 깔끔하게 즐기세요.",
  },
  {
    product_id: 10051,
    name: "저당 프로틴바 카라멜",
    brand: "원데이뉴트리션",
    category_id: 2,
    image_url: "https://picsum.photos/seed/bar1/400/500",
    is_active: true,
    quantity: 160,
    price: 2500,
    discount_rate: 20,
    original_price: 3100,
    created_at: "2025-01-22T09:00:00Z",
    updated_at: "2025-02-17T09:00:00Z",
    nutrition: {
      rawmtrl: "대두단백, 올리고당, 카카오버터, 카라멜시럽, 소금",
      allergymtrl: "대두, 우유",
      serving_size: 60,
      reference_intake: 1,
      food_weight: 60,
      calories_kcal: 200,
      protein_g: 20,
      fat_g: 7,
      ash_g: 1,
      carbohydrate_g: 18,
      sugar_g: 3,
      sodium_mg: 180,
      cholesterol_mg: 10,
      saturated_fat_g: 3,
      trans_fat_g: 0,
      gi: 30,
      gl: 3,
    },
    description: "당은 줄이고 단백질은 가득! 카라멜맛 저당 프로틴바로 맛있는 건강 간식을 즐겨보세요.",
  },
  {
    product_id: 10052,
    name: "유기농 두유 검은콩",
    brand: "삼육",
    category_id: 4,
    image_url: "https://picsum.photos/seed/soymilk1/400/500",
    is_active: true,
    quantity: 190,
    price: 1200,
    discount_rate: 0,
    original_price: 1200,
    created_at: "2025-02-08T09:00:00Z",
    updated_at: "2025-02-19T09:00:00Z",
    nutrition: {
      rawmtrl: "검은콩(국내산), 정제수, 설탕",
      allergymtrl: "대두",
      serving_size: 100,
      reference_intake: 1,
      food_weight: 190,
      calories_kcal: 65,
      protein_g: 3,
      fat_g: 2,
      ash_g: 0.5,
      carbohydrate_g: 9,
      sugar_g: 6,
      sodium_mg: 35,
      cholesterol_mg: 0,
      saturated_fat_g: 0.5,
      trans_fat_g: 0,
      gi: 32,
      gl: 3,
    },
    description: "국내산 유기농 검은콩으로 만든 고소한 두유. 매일 한 잔의 건강을 챙기세요.",
  },
  {
    product_id: 10053,
    name: "비타민 멀티팩",
    brand: "종근당",
    category_id: 7,
    image_url: "https://picsum.photos/seed/vitamin1/400/500",
    is_active: true,
    quantity: 500,
    price: 28900,
    discount_rate: 30,
    original_price: 41300,
    created_at: "2025-01-05T09:00:00Z",
    updated_at: "2025-02-10T09:00:00Z",
    nutrition: {
      rawmtrl: "비타민C, 비타민B군, 아연, 셀레늄, 비타민D",
      allergymtrl: "",
      serving_size: 1,
      reference_intake: 1,
      food_weight: 1,
      calories_kcal: 5,
      protein_g: 0,
      fat_g: 0,
      ash_g: 0,
      carbohydrate_g: 1,
      sugar_g: 0,
      sodium_mg: 0,
      cholesterol_mg: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      gi: 0,
      gl: 0,
    },
    description: "하루 한 포로 필수 비타민과 미네랄을 간편하게. 종합 영양 관리를 시작하세요.",
  },
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.product_id === id);
}

export function getProductsByCategory(categoryId: number): Product[] {
  return products.filter((p) => p.category_id === categoryId);
}

export function getCategoryById(id: number): Category | undefined {
  return categories.find((c) => c.category_id === id);
}

export function formatPrice(price: number): string {
  return price.toLocaleString("ko-KR");
}
